font_family      Iosevka Nerd Font
font_size 14
shell_integration  no-cursor
enable_audio_bell no
cursor_blink_interval 0


# BEGIN_KITTY_THEME
# One Dark
include current-theme.conf
# END_KITTY_THEME
