font_family      Agave Nerd Font
font_size 14
shell_integration  no-cursor
enable_audio_bell no
cursor_blink_interval 0

#background_opacity 0.95
foreground           #ae81ff 
background           #3f3f3f
cursor    #ff335c
url_color #0087bd
color0  #3b4252
color1  #bf616a
color2  #fd9353
color3  #ebcb8b
color4  #88c0d0
color5  #b48ead
color6  #88c0d0 
color7  #88c0d0
color8  #4c566a
color9  #bf616a
color10 #36c692
color11 #d08770
color12 #5e81ac
color13 #b48ead
color14 #8fbcbb
color15 #36c692
