backend = "glx";
paint-on-overlay = true;
glx-no-stencil = true;
glx-copy-from-front =false
glx-swap-method = 2;

#shadow = true;
#shadow-radius = 12;
#shadow-opacity = .75
#shadow-offset-x = -7;
#shadow-offset-x = -7;
#
#shadow-exclude = [
#  "class_g     = 'dwm'",
#]

corner-radius = 10
detect-rounded-corners = true;

rounded-corners-exclude = [
#  "class_g     = 'dwm'",
];

active-opacity = 1.0;
inactive-opacity = 1.0;
frame-opacity = 1.0;
inactive-opacity-override = false;

#blur-background = false;
#blur-method = "dual_kawase";
#blur-strength = 6;

# Fading
fading = true
fade-delta = 3
no-fading-openclose = false

fade-exclude = [ ];

# Application-specific settings; these override the default `active-opacity`
opacity-rule = [
#    "95:class_g = 'kitty' && focused",
#    "95:class_g = 'kitty' && !focused",
#    "95:class_g = 'Zathura' && focused",
#    "95:class_g = 'Zathura' && !focused",
#    "95:class_g = 'Insomnia' && focused",
#    "95:class_g = 'Insomnia' && !focused",
];

xrender-sync-fence = true;
