#! /bin/bash 

total_mem_kb=$(grep MemTotal /proc/meminfo | awk '{print $2}')

free_mem_kb=$(grep MemFree /proc/meminfo | awk '{print $2}')

used_mem_kb=$((total_mem_kb - free_mem_kb))

used_mem_percentage=$(awk "BEGIN {printf \"%.2f\", (${used_mem_kb} / ${total_mem_kb}) * 100}")

echo "^c#b97490^󰍛 ${used_mem_percentage}%  "
