#!/bin/sh

vol="$(wpctl get-volume @DEFAULT_AUDIO_SINK@)"

[ "$vol" != "${vol%\[MUTED\]}" ] && echo "^c#E95379^  " && exit

vol="${vol#Volume: }"

split() {
	IFS=$2
	set -- $1
	printf '%s' "$@"
}

vol="$(printf "%.0f" "$(split "$vol" ".")")"

case 1 in
	$((vol >= 70)) ) icon=" " ;;
	$((vol >= 30)) ) icon=" " ;;
	$((vol >= 1)) ) icon=" " ;;
	* ) echo "^c#E95379^  " && exit ;;
esac

echo "^c#E95379^ $icon$vol%"
